name: Windows

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:
    
env:
  BUILD_TYPE: Release

concurrency:
  group: "build_windows"
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: > 
          cmake
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DENABLE_SHARED=On
          -DENABLE_TESTS=On
          -DCMAKE_CXX_FLAGS='-w'
          .

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build .

      - name: Install
        working-directory: ${{github.workspace}}
        run: cmake --install .

      - name: Test
        working-directory: ${{github.workspace}}
        run: ./hephaudio_test.exe
        
