name: Linux

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:
    
env:
  BUILD_TYPE: Release

concurrency:
  group: "build_linux"
  cancel-in-progress: true

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install libasound2-dev
        run: sudo apt install -y libasound2-dev

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: > 
          cmake
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DENABLE_TESTS=On
          -DCMAKE_CXX_FLAGS='-w'
          .

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build .

      - name: Install
        working-directory: ${{github.workspace}}
        run: cmake --install .

      - name: Test
        working-directory: ${{github.workspace}}
        run: ./hephaudio_test

  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install libasound2-dev
        run: sudo apt install -y libasound2-dev

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: > 
          cmake
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DENABLE_TESTS=On
          -DCMAKE_CXX_FLAGS='-w'
          .

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build .

      - name: Install
        working-directory: ${{github.workspace}}
        run: cmake --install .

      - name: Test
        working-directory: ${{github.workspace}}
        run: ./hephaudio_test
